services:
  - type: web
    name: routeresq
    env: python
    buildCommand: cd client && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20.11.0
